version: "3.8"
services:
  http:
    container_name: http
    build: ./builds/http
    ports:
      - "8000:80"
    tty: true
    volumes:
      - ./builds/http/vhosts:/etc/apache2/sites-enabled
      - ./website:/var/www
      - ./var/logs/apache2:/var/log/apache2 # apache_logs
      - ./builds/http/files:/tmp/badges-credentials
    networks:
      - network
#  #Base de données MariaDB
#  db:
#    container_name: db
#    image: mariadb:10.5.8
#    restart: always
#    volumes:
#      - ./var/db-data:/var/lib/mysql
#      #- ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: app_db
#      TZ: Europe/Paris
#    networks:
#      - network
#  #PHP My Admin
#  phpmyadmin:
#    container_name: pma
#    image: phpmyadmin
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - "8081:80"
#    environment:
#      PMA_HOST: db
#    networks:
#      - network
#Network
networks:
  network: